FROM python:3.12-slim
WORKDIR /app

# Install system dependencies for pgvector/psycopg2
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

COPY ai-service/requirements.txt .
RUN pip install --no-cache-dir --default-timeout=1000 --retries 10  -r requirements.txt

COPY ai-service/ .

EXPOSE 8000
# Run FastAPI with uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
